/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 bat.glb 
Author: Danish shaikh (https://sketchfab.com/imdannyish)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mrf-cricket-bat-3d-model-fc0c63de3cfb4896bf5497b83359661a
Title: MRF Cricket bat 3D Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bat(props) {
  const { nodes, materials } = useGLTF('/Models/Bat/bat.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[3,15,0.75]}>
        <group>
          <mesh geometry={nodes.polySurface1_bat_face_0.geometry} material={materials.bat_face} />
          <mesh geometry={nodes.polySurface2_grip_0.geometry} material={materials.grip} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Bat/bat.glb')
