/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 drumset.glb 
Author: NovatoZ (https://sketchfab.com/NovatoZ)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/full-drum-set-b0aa40020cb645c2b4d6f68b31e5801d
Title: Full Drum set
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Drumset(props) {
  const { nodes, materials } = useGLTF('/Models/Drumset/Drumset.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[3.866, 41.239, -22.627]} rotation={[0, 0, -0.088]} scale={[40.986, 40.285, 20.643]}>
          <mesh geometry={nodes['BassDrum_���������������������_0'].geometry} material={materials.material} />
          <mesh geometry={nodes.BassDrum_White_0.geometry} material={materials.White} />
          <mesh geometry={nodes['BassDrum_���������������������_0_1'].geometry} material={materials.material_3} />
        </group>
        <group position={[3.866, 16.185, -47.307]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.217, 0.479, 7.76]}>
          <mesh geometry={nodes['���������������������������_���������������������_0'].geometry} material={materials.material} />
          <mesh geometry={nodes['���������������������������_White_0'].geometry} material={materials.White} />
        </group>
        <group position={[3.312, 81.835, -11.684]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.061, 4.869, 0.42]}>
          <mesh geometry={nodes['���������������������������������������_���������������������_0'].geometry} material={materials.material_3} />
          <mesh geometry={nodes['���������������������������������������_White_0'].geometry} material={materials.White} />
        </group>
        <group position={[23.844, 97.579, -26.748]} rotation={[-2.113, 0, 2.646]} scale={[16.214, 16.214, 10.352]}>
          <mesh geometry={nodes['Tom1_���������������������_0'].geometry} material={materials.material} />
          <mesh geometry={nodes.Tom1_White_0.geometry} material={materials.White} />
          <mesh geometry={nodes['Tom1_���������������������_0_1'].geometry} material={materials.material_3} />
        </group>
        <group position={[-19.417, 98.951, -25.567]} rotation={[-2.157, 0, 2.646]} scale={[17.215, 17.215, 10.999]}>
          <mesh geometry={nodes['Tom2_���������������������_0'].geometry} material={materials.material} />
          <mesh geometry={nodes.Tom2_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes['Tom2_���������������������001_0'].geometry} material={materials['.001']} />
        </group>
        <group position={[-66.002, 22.54, -75.443]} rotation={[-Math.PI / 2, 0, 0.543]} scale={[1.313, 1.313, 21.804]}>
          <mesh geometry={nodes.Floortom_White_0.geometry} material={materials.White} />
          <mesh geometry={nodes['Floortom_���������������������_0'].geometry} material={materials.material} />
          <mesh geometry={nodes.Floortom_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes['Floortom_���������������������002_0'].geometry} material={materials['.002']} />
          <mesh geometry={nodes.Floortom_Material004_0.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes['Floortom_���������������������004_0'].geometry} material={materials['.004']} />
          <mesh geometry={nodes.Floortom_Material005_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes['Floortom_���������������������005_0'].geometry} material={materials['.005']} />
        </group>
        <group position={[87.724, 19.471, -88.287]} rotation={[0.57, -0.375, 0.23]} scale={[1.324, 2.791, 1.548]}>
          <mesh geometry={nodes.Cube_White_0.geometry} material={materials.White} />
          <mesh geometry={nodes['Cube_���������������������001_0'].geometry} material={materials['.001_0']} />
        </group>
        <group position={[90.751, 19.471, -75.412]} rotation={[2.201, -0.901, 2.32]} scale={[1.324, 2.791, 1.548]}>
          <mesh geometry={nodes.Cube001_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes['Cube001_���������������������007_0'].geometry} material={materials['.007']} />
        </group>
        <group position={[78.696, 19.471, -68.945]} rotation={[2.572, 0.375, -2.911]} scale={[1.324, 2.791, 1.548]}>
          <mesh geometry={nodes.Cube002_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes['Cube002_���������������������008_0'].geometry} material={materials['.008']} />
        </group>
        <group position={[74.555, 19.471, -82.972]} rotation={[0.941, 0.901, -0.822]} scale={[1.324, 2.791, 1.548]}>
          <mesh geometry={nodes.Cube003_Material009_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes['Cube003_���������������������009_0'].geometry} material={materials['.009']} />
        </group>
        <group position={[32.639, 3.952, -66.995]} rotation={[-1.513, 0, 0.263]} scale={[0.899, 0.354, 5.736]}>
          <mesh geometry={nodes['���������������������������001_���������������������_0'].geometry} material={materials.material} />
          <mesh geometry={nodes['���������������������������001_White_0'].geometry} material={materials.White} />
        </group>
        <group position={[45.847, 58.105, -69.216]} rotation={[-1.62, -0.069, 2.752]} scale={[21.697, 21.697, 7.552]}>
          <mesh geometry={nodes['Snare_���������������������_0'].geometry} material={materials.material} />
          <mesh geometry={nodes.Snare_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes['Snare_���������������������003_0'].geometry} material={materials['.003']} />
        </group>
        <group position={[45.474, 27.784, -70.728]} rotation={[Math.PI / 2, 0, -0.672]} scale={[-1.521, 1.521, 23.192]}>
          <mesh geometry={nodes['������������������snare_White_0'].geometry} material={materials.White} />
          <mesh geometry={nodes['������������������snare_���������������������003_0'].geometry} material={materials['.003_0']} />
        </group>
        <group position={[87.556, 17.933, -44.373]} rotation={[1.532, -0.457, 1.343]} scale={[1.324, 4.449, 1.908]}>
          <mesh geometry={nodes.Cube004_Material011_0.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes['Cube004_���������������������012_0'].geometry} material={materials['.012']} />
        </group>
        <group position={[61.849, 17.933, -17.604]} rotation={[2.001, 0.165, -2.938]} scale={[1.324, 4.449, 1.908]}>
          <mesh geometry={nodes.Cube005_Material012_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes['Cube005_���������������������013_0'].geometry} material={materials['.013']} />
        </group>
        <group position={[48.099, 17.675, -49.302]} rotation={[1.264, 0.378, -0.962]} scale={[1.324, 4.449, 1.908]}>
          <mesh geometry={nodes.Cube006_Material013_0.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes['Cube006_���������������������014_0'].geometry} material={materials['.014']} />
        </group>
        <group position={[-69.85, 17.675, -20.008]} rotation={[1.122, 0.183, -0.461]} scale={[1.324, 4.449, 1.908]}>
          <mesh geometry={nodes.Cube013_Material010_0.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes['Cube013_���������������������011_0'].geometry} material={materials['.011']} />
        </group>
        <group position={[-73.602, 17.933, 14.341]} rotation={[1.87, 0.354, -2.438]} scale={[1.324, 4.449, 1.908]}>
          <mesh geometry={nodes.Cube014_Material014_0.geometry} material={materials['Material.014']} />
          <mesh geometry={nodes['Cube014_���������������������017_0'].geometry} material={materials['.017']} />
        </group>
        <group position={[-38.013, 17.933, 3.814]} rotation={[1.778, -0.413, 1.913]} scale={[1.324, 4.449, 1.908]}>
          <mesh geometry={nodes.Cube015_Material015_0.geometry} material={materials['Material.015']} />
          <mesh geometry={nodes['Cube015_���������������������018_0'].geometry} material={materials['.018']} />
        </group>
        <group position={[-99.398, 17.675, -28.695]} rotation={[1.165, 0.266, -0.649]} scale={[1.324, 4.449, 1.908]}>
          <mesh geometry={nodes.Cube019_Material016_0.geometry} material={materials['Material.016']} />
          <mesh geometry={nodes['Cube019_���������������������022_0'].geometry} material={materials['.022']} />
        </group>
        <group position={[-96.194, 17.933, 5.709]} rotation={[1.933, 0.288, -2.639]} scale={[1.324, 4.449, 1.908]}>
          <mesh geometry={nodes.Cube020_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes['Cube020_���������������������023_0'].geometry} material={materials['.023']} />
        </group>
        <group position={[-63.434, 17.933, -11.732]} rotation={[1.686, -0.445, 1.695]} scale={[1.324, 4.449, 1.908]}>
          <mesh geometry={nodes.Cube021_Material018_0.geometry} material={materials['Material.018']} />
          <mesh geometry={nodes['Cube021_���������������������024_0'].geometry} material={materials['.024']} />
        </group>
        <group position={[4.314, 11.182, -81.941]} rotation={[2.31, -0.302, 2.877]} scale={[1.258, 1.881, 0.791]}>
          <mesh geometry={nodes.Cube023_White_0.geometry} material={materials.White} />
          <mesh geometry={nodes['Cube023_���������������������001_0'].geometry} material={materials['.001_0']} />
        </group>
        <group position={[-7.885, 11.216, -92.488]} rotation={[1.426, 0.746, -1.308]} scale={[1.258, 1.881, 0.791]}>
          <mesh geometry={nodes.Cube024_White_0.geometry} material={materials.White} />
          <mesh geometry={nodes['Cube024_���������������������001_0'].geometry} material={materials['.001_0']} />
        </group>
        <group position={[9.246, 11.102, -95.891]} rotation={[1.003, -0.587, 0.715]} scale={[1.258, 1.881, 0.791]}>
          <mesh geometry={nodes.Cube025_White_0.geometry} material={materials.White} />
          <mesh geometry={nodes['Cube025_���������������������001_0'].geometry} material={materials['.001_0']} />
        </group>
        <mesh geometry={nodes['���������������������2_plankwood_0'].geometry} material={materials.plankwood} position={[-40.971, 64.336, -65.62]} rotation={[-3.127, -0.209, -3.104]} scale={[-1.196, 1.181, 26.427]} />
        <mesh geometry={nodes['���������������������1_plankwood_0'].geometry} material={materials.plankwood} position={[-43.636, 64.336, -65.433]} rotation={[-3.127, -0.209, -3.104]} scale={[-1.196, 1.181, 26.427]} />
        <mesh geometry={nodes['Cylinder_���������������������_0'].geometry} material={materials.material} position={[83.571, 54.405, -79.39]} rotation={[-Math.PI / 2, 0, -0.437]} scale={[1.316, 1.316, 43.101]} />
        <mesh geometry={nodes['Cylinder003_���������������������������_0'].geometry} material={materials.material_20} position={[83.571, 50.732, -79.39]} rotation={[-Math.PI / 2, 0, -0.437]} scale={[1.443, 1.443, 47.247]} />
        <mesh geometry={nodes['Cylinder004_���������������������_0'].geometry} material={materials.material} position={[83.571, 54.127, -79.39]} rotation={[-Math.PI / 2, 0, -0.437]} scale={[1.316, 1.316, 43.101]} />
        <mesh geometry={nodes.Cube022__0.geometry} material={materials['Cube.022__0']} position={[83.571, 7.732, -79.53]} rotation={[-Math.PI / 2, 0, 0.25]} scale={[3.376, 0.596, 6.062]} />
        <mesh geometry={nodes['���������������������������002_���������������������_0'].geometry} material={materials.material} position={[26.814, 3.952, -66.995]} rotation={[-1.513, 0.001, 0.276]} scale={[0.899, 0.354, 5.736]} />
        <mesh geometry={nodes.Cylinder001__0.geometry} material={materials['Cube.022__0']} position={[66.792, 60.073, -39.359]} rotation={[Math.PI / 2, 0, 0]} scale={[-1.232, 1.232, 64.585]} />
        <mesh geometry={nodes['Cylinder002_���������������������_0'].geometry} material={materials.material} position={[67.156, 26.399, -39.538]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.642, 3.642, 0.951]} />
        <mesh geometry={nodes.Cube007__0.geometry} material={materials['Cube.022__0']} position={[64.315, 14.522, -29.609]} rotation={[1.231, 0.146, -2.956]} scale={[1.381, 11.847, 0.416]} />
        <mesh geometry={nodes.Cube008__0.geometry} material={materials['Cube.022__0']} position={[75.806, 14.522, -41.199]} rotation={[-Math.PI / 2, -0.322, -1.33]} scale={[1.381, 11.847, 0.416]} />
        <mesh geometry={nodes.Cube009__0.geometry} material={materials['Cube.022__0']} position={[56.544, 14.03, -45.06]} rotation={[-Math.PI / 2, 0.212, 1.082]} scale={[1.381, 11.847, 0.416]} />
        <mesh geometry={nodes['Cylinder005_���������������������015_0'].geometry} material={materials['.015']} position={[67.156, 12.926, -39.538]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.642, 3.642, 1.477]} />
        <mesh geometry={nodes['Cylinder006_���������������������������_0'].geometry} material={materials.material_20} position={[66.168, 81.689, -32.697]} rotation={[-1.818, 0, -0.437]} scale={[1.725, 1.725, 56.475]} />
        <mesh geometry={nodes['Sphere_���������������������001_0'].geometry} material={materials['.001_0']} position={[66.792, 125.691, -39.359]} rotation={[-Math.PI / 2, 0, 0]} scale={3.521} />
        <mesh geometry={nodes.Cylinder007_Material013_0.geometry} material={materials['Material.013']} position={[66.792, 127.81, -41.105]} rotation={[0.741, 0, 0]} scale={[-0.842, 1.047, 9.493]} />
        <mesh geometry={nodes['Cylinder008_���������������������001_0'].geometry} material={materials['.001_0']} position={[66.792, 131.156, -44.771]} rotation={[0.736, -0.104, -0.114]} scale={[-1.175, 1.461, 3.023]} />
        <mesh geometry={nodes['���������������_���������������������_0'].geometry} material={materials.material} position={[76.57, 77.483, -38.713]} rotation={[-Math.PI / 2, 0, -0.437]} scale={[1.316, 1.316, 43.101]} />
        <mesh geometry={nodes['Sphere001_���������������������019_0'].geometry} material={materials['.019']} position={[-58.534, 125.691, -2.112]} rotation={[-Math.PI / 2, 0, -0.518]} scale={3.521} />
        <mesh geometry={nodes['Cylinder009_���������������������019_0'].geometry} material={materials['.019']} position={[-55.854, 131.156, -6.814]} rotation={[0.848, -0.472, 0.269]} scale={[-1.175, 1.461, 3.023]} />
        <mesh geometry={nodes.Cylinder010_Material010_0.geometry} material={materials['Material.010']} position={[-57.67, 127.81, -3.629]} rotation={[0.812, -0.374, 0.367]} scale={[-0.842, 1.047, 9.493]} />
        <mesh geometry={nodes['Cylinder011_���������������������������001_0'].geometry} material={materials['.001_33']} position={[-62.376, 76.861, 3.366]} rotation={[-1.787, 0.122, -0.942]} scale={[1.884, 1.884, 61.692]} />
        <mesh geometry={nodes['Cylinder012_���������������������010_0'].geometry} material={materials['.010']} position={[-58.13, 12.926, -2.087]} rotation={[-Math.PI / 2, 0, -0.518]} scale={[3.642, 3.642, 1.477]} />
        <mesh geometry={nodes['Cylinder013_���������������������020_0'].geometry} material={materials['.020']} position={[-58.13, 26.399, -2.087]} rotation={[-Math.PI / 2, 0, -0.518]} scale={[3.642, 3.642, 0.951]} />
        <mesh geometry={nodes.Cylinder014__0.geometry} material={materials['Cube.022__0']} position={[-58.534, 60.073, -2.112]} rotation={[Math.PI / 2, 0, 0.518]} scale={[-1.232, 1.232, 64.585]} />
        <mesh geometry={nodes.Cube010__0.geometry} material={materials['Cube.022__0']} position={[-64.614, 14.03, -12.139]} rotation={[-1.465, 0.184, 0.554]} scale={[1.381, 11.847, 0.416]} />
        <mesh geometry={nodes.Cube011__0.geometry} material={materials['Cube.022__0']} position={[-49.792, 14.522, 0.753]} rotation={[-1.735, -0.279, -1.871]} scale={[1.381, 11.847, 0.416]} />
        <mesh geometry={nodes.Cube012__0.geometry} material={materials['Cube.022__0']} position={[-65.515, 14.522, 5.132]} rotation={[1.203, -0.037, -2.47]} scale={[1.381, 11.847, 0.416]} />
        <mesh geometry={nodes['���������������001_���������������������027_0'].geometry} material={materials['.027']} position={[-48.752, 77.483, -1.452]} rotation={[-Math.PI / 2, 0, -0.437]} scale={[1.316, 1.316, 43.101]} />
        <mesh geometry={nodes['���������������002_���������������������028_0'].geometry} material={materials['.028']} position={[-74.981, 54.988, -12.774]} rotation={[-Math.PI / 2, 0, -0.437]} scale={[1.316, 1.316, 23.701]} />
        <mesh geometry={nodes['Cylinder018_���������������������021_0'].geometry} material={materials['.021']} position={[-84.326, 12.926, -13.485]} rotation={[-Math.PI / 2, 0, -0.316]} scale={[3.642, 3.642, 1.477]} />
        <mesh geometry={nodes['Cylinder019_���������������������026_0'].geometry} material={materials['.026']} position={[-84.326, 26.399, -13.485]} rotation={[-Math.PI / 2, 0, -0.316]} scale={[3.642, 3.642, 0.951]} />
        <mesh geometry={nodes.Cylinder020__0.geometry} material={materials['Cube.022__0']} position={[-84.727, 38.331, -13.428]} rotation={[Math.PI / 2, 0, 0.316]} scale={[-1.203, 1.203, 39.675]} />
        <mesh geometry={nodes.Cube016__0.geometry} material={materials['Cube.022__0']} position={[-92.692, 14.03, -22.034]} rotation={[-1.504, 0.201, 0.758]} scale={[1.381, 11.847, 0.416]} />
        <mesh geometry={nodes.Cube017__0.geometry} material={materials['Cube.022__0']} position={[-75.588, 14.522, -12.371]} rotation={[-1.674, -0.306, -1.662]} scale={[1.381, 11.847, 0.416]} />
        <mesh geometry={nodes.Cube018__0.geometry} material={materials['Cube.022__0']} position={[-90.115, 14.522, -4.932]} rotation={[1.203, 0.036, -2.658]} scale={[1.381, 11.847, 0.416]} />
        <mesh geometry={nodes.Cylinder015__0.geometry} material={materials['Cube.022__0']} position={[-84.708, 78.389, -13.157]} rotation={[-2.451, 0.516, -0.387]} scale={[0.606, 0.575, 16.324]} />
        <mesh geometry={nodes['Sphere002_���������������������026_0'].geometry} material={materials['.026']} position={[-84.771, 77.76, -13.106]} rotation={[-Math.PI / 2, 0, -0.518]} scale={2.63} />
        <mesh geometry={nodes['Sphere003_���������������������030_0'].geometry} material={materials['.030']} position={[-76.679, 86.93, -23.78]} rotation={[-Math.PI / 2, 0, -0.518]} scale={1.751} />
        <mesh geometry={nodes.Cylinder016_Material007_0.geometry} material={materials['Material.007']} position={[-73.614, 90.038, -29.292]} rotation={[-2.558, 0.478, -0.137]} scale={[0.606, 0.575, 5.763]} />
        <mesh geometry={nodes['Cylinder017_���������������������������003_0'].geometry} material={materials['.003_52']} position={[-78.933, 32.597, -18.354]} rotation={[-1.85, 0.122, -0.942]} scale={[1.999, 1.999, 65.461]} />
        <mesh geometry={nodes['Cylinder021_���������������������001_0'].geometry} material={materials['.001_0']} position={[-73.614, 90.038, -29.292]} rotation={[-2.558, 0.478, -0.137]} scale={[0.692, 0.643, 5.206]} />
        <mesh geometry={nodes['Cylinder022_���������������������005_0'].geometry} material={materials['.005']} position={[2.111, 31.679, -90.585]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.856, 16.856, 5.288]} />
        <mesh geometry={nodes.Cylinder023__0.geometry} material={materials['Cube.022__0']} position={[2.111, 15.403, -90.585]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.749, 1.749, 11.86]} />
        <mesh geometry={nodes['Cylinder024_���������������������031_0'].geometry} material={materials['.031']} position={[1.914, 4.922, -90.296]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.642, 3.642, 1.477]} />
        <mesh geometry={nodes['Cylinder025_���������������������032_0'].geometry} material={materials['.032']} position={[1.914, 16.65, -90.296]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.642, 3.642, 0.951]} />
        <mesh geometry={nodes.Cube026__0.geometry} material={materials['Cube.022__0']} position={[6.516, 7.429, -93.85]} rotation={[-1.141, -0.483, -0.792]} scale={[0.656, 5.284, 0.363]} />
        <mesh geometry={nodes.Cube027__0.geometry} material={materials['Cube.022__0']} position={[-4.552, 7.429, -91.696]} rotation={[-1.412, 0.618, 1.301]} scale={[0.656, 5.284, 0.363]} />
        <mesh geometry={nodes.Cube028__0.geometry} material={materials['Cube.022__0']} position={[2.885, 7.429, -85.412]} rotation={[-2.169, -0.227, -2.823]} scale={[0.656, 5.284, 0.363]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Drumset/Drumset.glb')
