/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 football.glb 
Author: Da-Luna (https://sketchfab.com/da-luna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/football-96dbd11f9f104134aef9a20ef50b55e9
Title: Football
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Football(props) {
  const { nodes, materials } = useGLTF('/Models/Football/football.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Soccerball__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Football/football.glb')
