/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Spaceship.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Spaceship(props) {
  const { nodes, materials } = useGLTF('/Models/Spaceship/Spaceship.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lo_poly_Spaceship_03_by_Liz_Reddington_1.geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes.Lo_poly_Spaceship_03_by_Liz_Reddington_1_1.geometry} material={materials.lambert3SG} />
      <mesh geometry={nodes.Lo_poly_Spaceship_03_by_Liz_Reddington_1_2.geometry} material={materials.lambert2SG} />
    </group>
  )
}

useGLTF.preload('/Models/Spaceship/Spaceship.glb')
