/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: Samuel Metters (https://sketchfab.com/samuelmetters)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-spaceships-9177fe4356e4451485dc6129c9904eb9
Title: Low Poly Spaceships
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Spaceship(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-4.538, 3.261, -4.408]}>
          <mesh geometry={nodes['Box002_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
          <mesh geometry={nodes['Box002_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          <mesh geometry={nodes['Box002_Material_#25_0'].geometry} material={materials.Material_25} />
          <mesh geometry={nodes['Box002_Material_#26_0'].geometry} material={materials.Material_26} />
          <mesh geometry={nodes['Box002_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          <mesh geometry={nodes['Box002_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
        </group>
      </group>
      <group position={[-40, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 2.119, -3.695]}>
          <mesh geometry={nodes['Box001_03_-_Default_0'].geometry} material={materials['03_-_Default_0']} />
          <mesh geometry={nodes['Box001_01_-_Default_0'].geometry} material={materials['01_-_Default_0']} />
          <mesh geometry={nodes['Box001_02_-_Default_0'].geometry} material={materials['02_-_Default_0']} />
          <mesh geometry={nodes['Box001_Material_#25_0'].geometry} material={materials.Material_25_0} />
          <mesh geometry={nodes['Box001_08_-_Default_0'].geometry} material={materials['08_-_Default_0']} />
        </group>
      </group>
      <group position={[40, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-4.538, 3.261, -4.07]}>
          <mesh geometry={nodes['Box003_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
          <mesh geometry={nodes['Box003_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          <mesh geometry={nodes['Box003_Material_#25_0'].geometry} material={materials.Material_25} />
          <mesh geometry={nodes['Box003_Material_#26_0'].geometry} material={materials.Material_26} />
          <mesh geometry={nodes['Box003_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          <mesh geometry={nodes['Box003_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
