/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 StingerDrone.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Drone(props) {
  const { nodes, materials } = useGLTF('/Models/StingerDrone.glb')
  return (
    <group 
      animate={{x:0,y:0,z:7}}
      transition={{duration:3}}
    {...props} dispose={null}>
      <mesh geometry={nodes.mesh1129617186.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1129617186_1.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh900292859.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh900292859_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1173527014.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1173527014_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1927891841.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1927891841_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh964036273.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh964036273_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh964036273_2.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh964036273_3.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh602833473.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh602833473_1.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1977848737.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1977848737_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1977848737_2.geometry} material={materials.mat8} />
    </group>
  )
}

useGLTF.preload('/Models/StingerDrone.glb')
