/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 balloon.glb 
Author: stormsurgestudio (https://sketchfab.com/stormsurgestudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-hot-air-balloon-3eff436e33ce4db3a54d4d8edc43528b
Title: Low poly hot air balloon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Balloon(props) {
  const { nodes, materials } = useGLTF('/Models/Balloon/balloon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Models/Balloon/balloon.glb')
