/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export function Cloud(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry}>
        <meshStandardMaterial
          {...materials["lambert2SG.001"]}
          transparent
          opacity={0.5}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/model.glb')
