/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Telescope.glb 
Author: sieminskaola (https://sketchfab.com/sieminskaola)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/telescope-fd6863dd22874707b99b00af620fdfcc
Title: Telescope
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Telescope(props) {
  const { nodes, materials } = useGLTF('/Models/Telescope/Telescope.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['All003_Material_#25_0'].geometry} material={materials.Material_25} rotation={[-Math.PI / 2, 0, 0]} scale={10} />
          <mesh geometry={nodes['All004_Material_#2_0'].geometry} material={materials.Material_2} rotation={[-Math.PI / 2, 0, 0]} scale={10} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Telescope/Telescope.glb')
